name: Channel Diff and Review

on:
  pull_request:
  issue_comment:
    types: [created]  # run when comment added with "ðŸ“¦"

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  crawl_package:
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request != null && contains(github.event.comment.body, 'ðŸ“¦')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Diff and review changed/added packages
        uses: kaste/st_package_reviewer/gh_action@pr-comments
        with:
          pr: ${{ github.event.pull_request.html_url }}
      
